# Generated by Django 4.2.7 on 2023-12-22 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ccode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capcode', models.IntegerField()),
                ('capname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app2.country')),
            ],
        ),
    ]
